# Generated by Django 5.2.6 on 2025-09-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("editions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="")),
                ("video_title", models.CharField(max_length=200)),
                (
                    "video_thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="videos/thumbnail/"
                    ),
                ),
                ("video_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videos",
                        to="editions.edition",
                    ),
                ),
            ],
            options={
                "ordering": ["video_title"],
            },
        ),
    ]
