# Generated by Django 5.2.6 on 2025-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="videos/original/"),
        ),
    ]
