# Generated by Django 5.2.6 on 2025-09-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_alter_video_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="media/videos/original/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/videos/thumbnail/"
            ),
        ),
    ]
