# Generated by Django 5.2.6 on 2025-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_alter_video_video_file_alter_video_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_thumbnail",
            field=models.ImageField(upload_to="media/videos/thumbnail/"),
        ),
    ]
