# Generated by Django 5.2.6 on 2025-09-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0005_alter_video_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_title",
            field=models.CharField(max_length=300),
        ),
    ]
