# Generated by Django 5.2.6 on 2025-09-14 21:05

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_file",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="photos/processed/"
            ),
        ),
    ]
