# Generated by Django 5.2.6 on 2025-09-17 12:27

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_alter_photo_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_file",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="media/photos/processed/"
            ),
        ),
    ]
