# Generated by Django 5.2.6 on 2025-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edition_name", models.CharField(max_length=200, unique=True)),
                ("edition_description", models.TextField()),
                ("preview_image1", models.ImageField(upload_to="")),
                ("preview_image2", models.ImageField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["edition_name"],
            },
        ),
    ]
