# Generated by Django 5.2.6 on 2025-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="preview_image1",
            field=models.ImageField(upload_to="editions/previews/"),
        ),
        migrations.AlterField(
            model_name="edition",
            name="preview_image2",
            field=models.ImageField(upload_to="editions/previews/"),
        ),
    ]
