# Generated by Django 5.2.6 on 2025-09-17 12:27

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("editions", "0002_alter_edition_preview_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="preview_image1",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="media/editions/previews/"
            ),
        ),
        migrations.AlterField(
            model_name="edition",
            name="preview_image2",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="media/editions/previews/"
            ),
        ),
    ]
