# Generated by Django 5.2.6 on 2025-10-26 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("editions", "0003_alter_edition_preview_image1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edition",
            options={"ordering": ["-created_at"]},
        ),
    ]
