# Generated by Django 5.2.6 on 2026-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editions", "0004_alter_edition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
