# Generated by Django 5.2.6 on 2026-01-15 11:23

from django.db import migrations
from django.utils.text import slugify


def gen_slugs(apps, schema_editor):
    Edition = apps.get_model('editions', 'Edition')
    for row in Edition.objects.all():
        if not row.slug:
            row.slug= slugify(row.edition_name)
            row.save()


class Migration(migrations.Migration):
    dependencies = [
        ("editions", "0005_edition_slug"),
    ]

    operations =  [
    migrations.RunPython(gen_slugs, reverse_code=migrations.RunPython.noop),
    ]
