# Generated by Django 5.2.6 on 2025-09-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulespagecontents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rulespagecontent",
            options={"verbose_name_plural": "Rules Page Contents"},
        ),
        migrations.RemoveField(
            model_name="rulespagecontent",
            name="featured_image",
        ),
        migrations.AddField(
            model_name="rulespagecontent",
            name="pdf_file_mobtec",
            field=models.FileField(blank=True, null=True, upload_to="rules/pdfs/"),
        ),
        migrations.AddField(
            model_name="rulespagecontent",
            name="pdf_file_mobvap",
            field=models.FileField(blank=True, null=True, upload_to="rules/pdfs/"),
        ),
    ]
