# Generated by Django 5.2.6 on 2025-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_title", models.CharField(max_length=200)),
                ("youtube_url", models.URLField(max_length=300)),
                ("block_content1_title", models.CharField(max_length=200)),
                ("block_content1_text", models.TextField()),
                ("youtube_url2", models.URLField(max_length=300)),
                ("block_content2_title", models.CharField(max_length=200)),
                ("block_content2_text", models.TextField()),
                ("schedule_table_html", models.TextField()),
                ("block_content3_title", models.CharField(max_length=200)),
                ("block_content3_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
