# Generated by Django 5.2.6 on 2025-09-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepagecontents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="block_content4_text",
            field=models.TextField(blank=True, default=".", null=True),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="block_content4_title",
            field=models.CharField(blank=True, default=".", max_length=200),
        ),
    ]
