# Generated by Django 5.2.6 on 2025-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepagecontents", "0002_homepagecontent_block_content4_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="schedule_table_title",
            field=models.CharField(blank=True, null=True),
        ),
    ]
