# Generated by Django 5.2.6 on 2025-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepagecontents", "0003_homepagecontent_schedule_table_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecontent",
            name="youtube_url2",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
